{{- if .Values.config.oauthClientID }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencompat.fullname" . }}
  labels:
    {{- include "opencompat.labels" . | nindent 4 }}
type: Opaque
stringData:
  OPENCOMPAT_OAUTH_CLIENT_ID: {{ .Values.config.oauthClientID | quote }}
{{- end }}
